# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsoCreds < Formula
  desc "Get AWS SSO temporary creds from an SSO profile. Includes set as the default profile inside the credentials and login flag"
  homepage "https://www.linkedin.com/in/alejandro-blanco-m-b847244b/"
  version "1.2.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/alecuba16/aws-sso-creds-default-login/releases/download/v1.2.7/aws-sso-creds-v1.2.7-darwin-arm64.tar.gz"
      sha256 "35c371f11197fa48189d864c53dcb08a829f3da755eeb334812232a708e2bc14"

      def install
        bin.install "aws-sso-creds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alecuba16/aws-sso-creds-default-login/releases/download/v1.2.7/aws-sso-creds-v1.2.7-darwin-amd64.tar.gz"
      sha256 "61121601cd6de23e3dcab3a42973c658ea809fafa3ef3bcc7c93e0368237e095"

      def install
        bin.install "aws-sso-creds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alecuba16/aws-sso-creds-default-login/releases/download/v1.2.7/aws-sso-creds-v1.2.7-linux-arm64.tar.gz"
      sha256 "200b58b51655abedb51272ee9bac6d2b56e3ad2c73542ac38b75dd473d732a3a"

      def install
        bin.install "aws-sso-creds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alecuba16/aws-sso-creds-default-login/releases/download/v1.2.7/aws-sso-creds-v1.2.7-linux-amd64.tar.gz"
      sha256 "2d191cda3e21a78926152ab5a3a2328d7219e271f2bcaa1f3b6c2ddbc7857cd8"

      def install
        bin.install "aws-sso-creds"
      end
    end
  end
end
