# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsoCreds < Formula
  desc "Get AWS SSO temporary creds from an SSO profile. Includes set as the default profile inside the credentials and login flag"
  homepage "https://github.com/alecuba16/aws-sso-creds-default-login"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alecuba16/aws-sso-creds-default-login/releases/download/v1.2.2/aws-sso-creds-v1.2.2-darwin-amd64.tar.gz"
      sha256 "93215f70bedd7013ee8e275ba07b2c4a3da33bbda3cd428de38f756c5d7d9294"

      def install
        bin.install "aws-sso-creds-default-login"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alecuba16/aws-sso-creds-default-login/releases/download/v1.2.2/aws-sso-creds-v1.2.2-darwin-arm64.tar.gz"
      sha256 "0fd07cd93df2f66dca3e4ae59afb5670b97e5f5e7f1ed4116dc49762e5962892"

      def install
        bin.install "aws-sso-creds-default-login"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alecuba16/aws-sso-creds-default-login/releases/download/v1.2.2/aws-sso-creds-v1.2.2-linux-arm64.tar.gz"
      sha256 "e64b390ceb94c4a6f487cf0d75da1f94c70677793110d5227fb3e95cc159379e"

      def install
        bin.install "aws-sso-creds-default-login"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alecuba16/aws-sso-creds-default-login/releases/download/v1.2.2/aws-sso-creds-v1.2.2-linux-amd64.tar.gz"
      sha256 "b271fe57c5fbb8abfc05f6cf5fb37d6707fc2e0ba3badc5588c69338463cc08b"

      def install
        bin.install "aws-sso-creds-default-login"
      end
    end
  end
end